### ISSUE TITLE
Suspcious use of Crypt::Random

### ISSUE THREAD

**Issue by kentfredric** [TLINDEN/Crypt--PWSafe3#10]
The following code block looks questionable, after discovering that the default of Crypt::Random is to *ensure* the highest bit of every generated number is 1.

Which in practice means:
```perl
my $i = makerandom( Size => 256, Strength => 1 );
```

$i can never be an integer lower than `2 ** 255`

eg: 
```perl
use Crypt::Random qw( makerandom );

my $yes = 0; 
my $no = 0;

for ( 1..10000 ) {
  my $bits = makerandom( Size => 256, Strength => 1 );
  if ( $bits < 2 ** 255 ) {
    $yes++
  } else {
    $no++;
  }
}
printf qq[yes: %d, no: %d\n], $yes, $no;
# yes: 0, no: 10000
```

https://metacpan.org/pod/Crypt::Random#Uniform-0-||-1

When `Uniform => 1`, the distribution is from `0 .. 2**Size` , not `2**(Size-1)+1 .. 2**Size`

```perl
use Crypt::Random qw( makerandom );

my $yes = 0; 
my $no = 0;

for ( 1..10000 ) {
  my $bits = makerandom( Size => 256, Strength => 1, Uniform => 1);
  if ( $bits < 2 ** 255 ) {
    $yes++
  } else {
    $no++;
  }
}
printf qq[yes: %d, no: %d\n], $yes, $no;
# yes: 5079, no: 4921
```

It also seems odd that you call the return value of this function `$bytes`, when [that function returns an **integer**](https://metacpan.org/pod/Crypt::Random#makerandom%28%29), and doing `substr()` on an integer is uh. Weird.

https://metacpan.org/source/TLINDEN/Crypt-PWSafe3-1.22/lib/Crypt/PWSafe3.pm#L60-64

**Comment by TLINDEN** [comment]
Commit b51bb9f should fix it.
