### ISSUE TITLE
random usage in stretchpw()

### ISSUE THREAD

**Issue by rfdrake** [TLINDEN/Crypt--PWSafe3#9]
I was investigating why something I wrote was hanging after a few runs and I discoverted it was because I was running out of entropy.  I further tracked this to using Crypt::Random and saw that Bytes::Random::Secure seems to be the better option.

However, I was still confused why it needed to generate a random number just to open an existing file.  I looked at how things worked and saw that read() was calling stretchpw() which had this line near the end:

    $passwd = $this->random(64);

This isn't returned from the sub and doesn't seemed to be referenced anywhere.  Commenting the line out seems to fix my issue, but might create problems in other places I don't know about.  If the intention is to overwrite the plaintext password in memory can you just zero it instead of using random?

I think my only alternative for my program would be to require Bytes::Random::Secure if they use Crypt::PWSafe3, since Crypt::Random can block silently in places without the user knowing why.

**Comment by TLINDEN** [comment]
Thanks for reporting. I fixed it on master. Could you try if it works better now?

Tom
